name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Create Android project structure
        
        run: flutter create . --platforms=android --project-name wchatalwzeer

      - name: Set minSdkVersion
        run: sed -i 's/flutter.minSdkVersion/23/' android/app/build.gradle
      - name: Update Kotlin version
        run: sed -i 's/ext.kotlin_version = .*/ext.kotlin_version = '\''1.9.0'\''/' android/build.gradle


      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

